version: "2"
checks:
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    config:
      threshold: 100
  nested-control-flow:
    enabled: false
  identical-code:
    enabled: false
plugins:
  pep8:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-5"
    config:
      config: client/.eslintrc.js
    checks:
      import/no-unresolved:
        enabled: false
      no-multiple-empty-lines: # TODO: Enable
        enabled: false
exclude_patterns:
- "tests/**/*.py"
- "migrations/**/*.py"
- "setup/**/*"
- "bin/**/*"
- "**/node_modules/"
- "client/dist/"
- "**/*.pyc"
