FROM cypress/browsers:chrome67

WORKDIR /usr/src/app

RUN npm install cypress > /dev/null

COPY cypress /usr/src/app/cypress
COPY cypress.json /usr/src/app/cypress.json

RUN ./node_modules/.bin/cypress verify
