[pytest]
norecursedirs = *.egg .eggs dist build docs .tox
pythonpath = .
filterwarnings =
    once::DeprecationWarning
    once::PendingDeprecationWarning
addopts = -v --tb=short --maxfail=10 --durations=10
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)8s] %(name)s: %(message)s
