# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"


# TODO: should be result of encryption of readable password
__pg_password = "securepass"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box     = "ubuntu-precise-cloudimg-amd64"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box"

  config.berkshelf.enabled    = true
  config.omnibus.chef_version = :latest

  config.vm.network "forwarded_port", guest: 8888, host: 9999
  
  
  config.vm.provision :chef_solo do |chef|
     # run apt-get update before anything else (specifically postgresql)..
     chef.add_recipe "apt"
     chef.add_recipe "postgresql"
     chef.add_recipe "redash::redash_pg_schema"
     chef.add_recipe "redash::redash"

     chef.json = {
       "apt"        => { "compiletime" => true },
       "postgresql" => { "password"    => { "postgres" => __pg_password } },
       "redash"     => { "db"          => { "host"     => "localhost",
                                            "user"     => "postgres",
                                            "password" => __pg_password } }
     }
   end
end
