# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.box = "precise32"

  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box"

  config.berkshelf.enabled = true
  #config.omnibus.chef_version = :latest
  config.omnibus.chef_version = "11.6.0"
  
  config.vm.network "forwarded_port", guest: 8888, host: 9999
  
  
  config.vm.provision :chef_solo do |chef|
     #Run apt-get update before anything else (specifically postgresql)..
     chef.add_recipe "apt"
     chef.add_recipe "redash"
     chef.add_recipe "postgresql"
     
     chef.json = {
       "apt"        => {"compiletime" => true},
       "postgresql" => {"password"    => {"postgres" => "securepass"}},
       "redash"     => {"db"          => {"host"     => "localhost"}},
     } 
     
   end
end
