FROM cypress/browsers:chrome67

ENV APP /usr/src/app
WORKDIR $APP

COPY package.json package-lock.json $APP/
COPY viz-lib $APP/viz-lib
RUN npm ci > /dev/null

COPY . $APP

RUN ./node_modules/.bin/cypress verify
