#!/bin/bash
if [ $CIRCLE_BRANCH = master ] || [ $CIRCLE_BRANCH = preview-build ]
then
    FULL_VERSION='preview'
else
    VERSION=$(jq -r .version package.json)
    FULL_VERSION=$VERSION.b$CIRCLE_BUILD_NUM
fi

echo $FULL_VERSION
