FROM cypress/browsers:chrome67

ENV APP /usr/src/app
WORKDIR $APP

COPY package.json $APP/package.json
COPY viz-lib/package.json $APP/viz-lib/package.json
RUN npm ci > /dev/null

COPY . $APP

RUN ./node_modules/.bin/cypress verify
