#!/bin/bash

# This script only needs to run on the main Redash repo

if [ "${GITHUB_REPOSITORY}" != "getredash/redash" ] && [ "${GITHUB_REPOSITORY}" != "justinclift/redash" ]; then # FIXME: Remove justinclift stuff
	echo "Skipping image build for Docker Hub, as this isn't the main Redash repository"
	exit 0
fi

#if [ "${GITHUB_REF_NAME}" != "master" ] && [ "${GITHUB_REF_NAME}" != "preview-image" ]; then
#	echo "Skipping image build for Docker Hub, as this isn't the 'master' nor 'preview-image' branch"
#	exit 0
#fi

set -e
VERSION=$(jq -r .version package.json)
VERSION_TAG="$VERSION.b${GITHUB_RUN_ID}.${GITHUB_RUN_NUMBER}"

export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=1

docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"

if [ "${GITHUB_REPOSITORY}" = "getredash/redash" ]; then # FIXME: Remove pgautoupgrade stuff
	DOCKERHUB_REPO="redash/redash"
  DOCKER_TAGS="-t redash/redash:preview -t redash/preview:${VERSION_TAG}"
else
	DOCKERHUB_REPO="pgautoupgrade/tempstuff"
  DOCKER_TAGS="-t pgautoupgrade/tempstuff:preview -t pgautoupgrade/tempstuff:${VERSION_TAG}"
fi

# Build the docker container
docker build --build-arg test_all_deps=true ${DOCKER_TAGS} .

# Push the container to the preview build locations
docker push "${DOCKERHUB_REPO}:preview"
if [ "${GITHUB_REPOSITORY}" = "getredash/redash" ]; then
	docker push "redash/preview:${VERSION_TAG}"
fi

echo "Built: ${VERSION_TAG}"
