FROM cypress/browsers:node18.12.0-chrome106-ff106

ENV APP /usr/src/app
WORKDIR $APP

RUN npm install -g pnpm@10.30.3

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc $APP/
COPY viz-lib $APP/viz-lib
RUN pnpm install --frozen-lockfile > /dev/null

COPY . $APP

RUN ./node_modules/.bin/cypress verify
