"""empty message

Revision ID: 10c921561479
Revises: e5c7a4e2df4d
Create Date: 2019-05-04 09:49:58.064887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c921561479'
down_revision = 'e5c7a4e2df4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboards', sa.Column('dashboard_filters_only', sa.Boolean(), nullable=False, server_default='f', default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboards', 'dashboard_filters_only')
    # ### end Alembic commands ###
