"""add_query_tags

Revision ID: 1730e2ac33a4
Revises: e7004224f284
Create Date: 2018-05-10 13:57:30.110413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1730e2ac33a4'
down_revision = 'e7004224f284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_tags',
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('query_id', 'tag_id')
    )
    op.alter_column(u'favorites', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'favorites', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('query_tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
