"""Add column metadata and table metadata

Revision ID: 280daa582976
Revises: 73beceabb948
Create Date: 2019-01-24 18:23:53.040608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280daa582976'
down_revision = '73beceabb948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('table_exists', sa.Boolean(), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('table_description', sa.String(length=4096), nullable=True),
    sa.Column('column_metadata', sa.Boolean(), nullable=False),
    sa.Column('sample_query', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('column_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('column_type', sa.String(length=255), nullable=True),
    sa.Column('column_example', sa.String(length=4096), nullable=True),
    sa.Column('column_exists', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['table_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('column_metadata')
    op.drop_table('table_metadata')
    # ### end Alembic commands ###
