"""add comment field to deployment run record

Revision ID: 52ced47b8e8c
Revises: aecf296f5b2b
Create Date: 2026-09-09 23:35:18.960316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ced47b8e8c'
down_revision = 'aecf296f5b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployment_runs', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployment_runs', 'comment')
    # ### end Alembic commands ###
