"""empty message

Revision ID: c6b6d7ec6dee
Revises: d1eae8b9893e
Create Date: 2017-07-27 03:47:57.747238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b6d7ec6dee'
down_revision = 'd1eae8b9893e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_results', sa.Column('data_scanned', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_results', 'data_scanned')
    # ### end Alembic commands ###
