"""empty message

Revision ID: cf135a57332e
Revises: 280daa582976
Create Date: 2019-02-05 19:52:48.233070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf135a57332e'
down_revision = '280daa582976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('column_metadata', sa.Column('column_description', sa.String(length=4096), nullable=True))
    op.add_column('table_metadata', sa.Column('table_visible', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_metadata', 'table_visible')
    op.drop_column('column_metadata', 'column_description')
    # ### end Alembic commands ###
