"""Add 'schedule_until' column to queries.

Revision ID: eb2f788f997e
Revises: d1eae8b9893e
Create Date: 2017-03-02 12:20:00.029066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb2f788f997e'
down_revision = 'd1eae8b9893e'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        'queries',
        sa.Column('schedule_until', sa.DateTime(timezone=True), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'schedule_until')
