"""add_alert_template_column

Revision ID: ed7bf6adbd4d
Revises: 71477dadd6ef
Create Date: 2018-11-28 22:56:40.494028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7bf6adbd4d'
down_revision = '71477dadd6ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('template', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'template')
    # ### end Alembic commands ###
